const links = {
  login: `/api/auth/login`,
  dataPull: `/api/operator/data/pull`,
  logout: `/api/operator/user/logout`,
  listTicket: `/api/operator/service/list/ticket`,
  workplaceActive: `/api/operator/workplace/activate`,
  workplaceList: `/api/operator/user/workplace/list`,
  branchList: `/api/operator/user/branch/list`,
  ticketRegister:  `/api/operator/ticket/register`,
  serviceGet: `/api/operator/service/get`,
  ticketCall: `/api/operator/ticket/call`,
  ticketStart: `/api/operator/ticket/start`,
  ticketFinish: `/api/operator/ticket/finish`,
  ticketDelete: `/api/operator/ticket/delete`,
  postponedList: `/api/operator/ticket/list/postponed`,
  activeList: `/api/operator/workplace/list/active`,
  serviceList: `/api/operator/service/list/internal`,
  ticketRedirect: `/api/operator/ticket/redirect`,
  internalOperationStart: `/api/operator/internal-operation/start`,
  internalOperationFinish: `/api/operator/internal-operation/finish`,
  postponForWhile: `/api/operator/ticket/postpone-for-while`,
  ticketPostpone: `/api/operator/ticket/postpone`,
  callPostponed: `/api/operator/ticket/call/postponed`,
};

export default links;
